sudo: False

language: generic

matrix:
  include:
    - env:
      - PYVER=3.5
    - env:
      - PYVER=3.6
    - env:
      - PYVER=3.7
    - env:
      - PYVER=3.8
    - arch: arm64
      env:
      - PYVER=3.8

install:
  # Install conda
  - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
      wget https://github.com/conda-forge/miniforge/releases/download/4.8.2-1/Miniforge3-4.8.2-1-Linux-aarch64.sh -O miniconda.sh;
      chmod +x miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi  
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

  # Install dependencies
  - conda create -n test -y -c conda-forge python=$PYVER pip botocore pytest
  - source activate test
  - export BOTO_CONFIG=/dev/null
  - export AWS_ACCESS_KEY_ID=foobar_key
  - export AWS_SECRET_ACCESS_KEY=foobar_secret
  - pip install moto
  - pip install git+https://github.com/intake/filesystem_spec/ --no-deps
  - conda list

script:
  - py.test -vv s3fs

notifications:
  email: false
